services:
  n8n:
    image: docker.io/n8nio/n8n:2.22.2
    restart: unless-stopped
    environment:
      GENERIC_TIMEZONE: ${GENERIC_TIMEZONE}
    ports:
      - "5678"
    volumes:
      - n8n-data:/home/node/.n8n
    networks: [suji-net]
    deploy:
      resources:
        limits:
          memory: 1024M
          cpus: "1.0"
volumes:
  n8n-data:
networks:
  suji-net:
    external: true
