services:
  ghost:
    image: docker.io/ghost:5.99.0-alpine
    restart: unless-stopped
    environment:
      url: ${URL}
      database__client: sqlite3
      database__connection__filename: /var/lib/ghost/content/data/ghost.db
    ports:
      - "2368"
    volumes:
      - ghost-content:/var/lib/ghost/content
    networks: [suji-net]
    deploy:
      resources:
        limits:
          memory: 1024M
          cpus: "1.0"
volumes:
  ghost-content:
networks:
  suji-net:
    external: true
